api = "0.7"

# General metadata about the buildpack that is used be the lifecycle
[buildpack]
  id = "renkulab/vscodium"
  name = "VSCodium Buildpack"
  version = "0.0.1"

[metadata]
  include-files = ["bin/run", "bin/detect", "bin/build", "buildpack.toml"]
  pre-package = "./scripts/build.sh"
[[metadata.dependencies]]
    checksum = "sha256:bf8ccb0781672bbd11820a97b3a8bc32f816e958620761d4ae2b2047393cee0a"
    id = "vscodium"
    licenses = ["MIT"]
    name = "VSCodium"
    uri = "https://github.com/VSCodium/vscodium/releases/download/1.97.2.25045/VSCodium-linux-x64-1.97.2.25045.tar.gz"
    stacks = ["io.buildpacks.stacks.jammy"]
    version = "1.97.2.25045"
# The list of stacks that the buildpack itself is compatible with
[[stacks]]
  id = "io.buildpacks.stacks.jammy"
