api = "0.8"

# General metadata about the buildpack that is used be the lifecycle
[buildpack]
id = "vscodium"
name = "VSCodium Buildpack"
version = "0.0.1"

[metadata]
include-files = [
  "buildpack.toml",
  "linux/amd64/bin/build",
  "linux/amd64/bin/detect",
  "linux/amd64/bin/run",
  "linux/amd64/bin/install-extensions",
  "linux/arm64/bin/build",
  "linux/arm64/bin/detect",
  "linux/arm64/bin/run",
  "linux/arm64/bin/install-extensions",
]
pre-package = "./scripts/build.sh --target linux/amd64 --target linux/arm64"

[metadata.default-versions]
vscodium = "1.104.36664"

[[metadata.dependencies]]
arch = "amd64"
os = "linux"
checksum = "sha256:01ec743298a377c404064c33cdcf18d936b43e939e0d2bc645e22e81b0ef4a18"
id = "vscodium"
licenses = ["MIT"]
name = "VSCodium"
uri = "https://github.com/VSCodium/vscodium/releases/download/1.96.4.25026/vscodium-reh-web-linux-x64-1.96.4.25026.tar.gz"
stacks = ["*"]
version = "1.96.4"

[[metadata.dependencies]]
arch = "arm64"
os = "linux"
checksum = "sha256:c2bcf0b138401967347294d8ed2bdf5d0d4eb823cd487ad14e6d52f61c768c8e"
id = "vscodium"
licenses = ["MIT"]
name = "VSCodium"
uri = "https://github.com/VSCodium/vscodium/releases/download/1.96.4.25026/vscodium-reh-web-linux-arm64-1.96.4.25026.tar.gz"
stacks = ["*"]
version = "1.96.4"

[[metadata.dependencies]]
arch = "amd64"
os = "linux"
checksum = "sha256:1176c6872c3feb8ccb10c91ed6a0c7c9ecefa15da36e0c6939dd2ab46f09468c"
id = "vscodium"
licenses = ["MIT"]
name = "VSCodium"
uri = "https://github.com/VSCodium/vscodium/releases/download/1.104.36664/vscodium-reh-web-linux-x64-1.104.36664.tar.gz"
stacks = ["*"]
version = "1.104.36664"

[[metadata.dependencies]]
arch = "arm64"
os = "linux"
checksum = "sha256:b315f5dcc0c25a044ddbba1e2508b656284981a3a7513b0ffed605b42ac09260"
id = "vscodium"
licenses = ["MIT"]
name = "VSCodium"
uri = "https://github.com/VSCodium/vscodium/releases/download/1.104.36664/vscodium-reh-web-linux-arm64-1.104.36664.tar.gz"
stacks = ["*"]
version = "1.104.36664"

[[metadata.dependency-constraints]]
constraint = "1.104.*"
id = "vscodium"
patches = 2

[metadata.version-lines]
stable = "1.104.*"
# The list of stacks that the buildpack itself is compatible with

[[stacks]]
id = "*"

[[targets]]
arch = "amd64"
os = "linux"

[[targets]]
arch = "arm64"
os = "linux"
