api = "0.8"

# General metadata about the buildpack that is used be the lifecycle
[buildpack]
id = "vscodium"
name = "VSCodium Buildpack"
version = "0.0.1"

[metadata]
include-files = ["bin/run", "bin/detect", "bin/build", "buildpack.toml"]
pre-package = "./scripts/build.sh"

[metadata.default-versions]
vscodium = "1.97.*"

[[metadata.dependencies]]
checksum = "sha256:95e6a874410075ccf6831657c2f1bac49d925fee34a0d1cf7e7973ef13ba87eb"
id = "vscodium"
licenses = ["MIT"]
name = "VSCodium"
uri = "https://github.com/VSCodium/vscodium/releases/download/1.97.2.25045/vscodium-reh-web-linux-x64-1.97.2.25045.tar.gz"
stacks = ["io.buildpacks.stacks.jammy"]
version = "1.97.2"

[[metadata.dependency-constraints]]
constraint = "1.97.*"
id = "vscodium"
patches = 2

[metadata.version-lines]
stable = "1.97.*"
# The list of stacks that the buildpack itself is compatible with

[[stacks]]
id = "io.buildpacks.stacks.jammy"
