name: Release
on:
  release:
    types: [published]
permissions:
  contents: write
jobs:
  build-and-publish-buildpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Package Buildpack
        run: make package version="${{ github.event.release.name }}"
      - name: Publish Buildpack
        uses: softprops/action-gh-release@v2
        with:
          files: build/*
