name: Tests

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    - closed

permissions:
  contents: read
jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.0
      - name: Tests
        run: |
          make lint && \
          make test
